# Generated by Django 3.2.8 on 2021-12-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211225_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='change',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_product', to='home.products')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var_product', to='home.variant')),
            ],
        ),
    ]
